name: fingerprint_aps
description: Project created to present the PHC work of the college in the sixth semester. This project was made with Flutter into a mobile application, using some libraries such as local_auth, hive, flutter_modular, flutter_bloc, etc. This project was make with clean architecture. 

publish_to: 'none'
version: 1.0.7+7

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  asuka: 2.0.0-nullsafety.3
  auto_size_text: 3.0.0-nullsafety.0
  bloc: ^7.2.0
  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_modular: ^3.4.1+1
  flutter_native_splash: ^1.2.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  local_auth: 1.1.6

dev_dependencies:
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fingerprint.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/